version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-dodge-the-blocks_server_1
      APP_PORT: 8000

  server:
    image: gbletsch/web-dodge-the-blocks:1.0.7
    user: "1000:1000"
    init: true
